### ISSUE TITLE
More options for branch name detection

### ISSUE THREAD

**Issue by paour** [dagio/post-jira-comment-with-build-details#1]
In IssueKeyResolver, could you add more patterns, like:

- `bugfix`, `bug` in addition to `hotfix` and `release` as a prefix
- since the project will usually always be the same for a given workflow, why note make the project token configurable in the step UI, like the Git branch name. I'd like to be able to keep using short branch names such as `bug/id-description` where `id` is the Jira issue number

To make it even more configurable, an upstream step could also provide the JIRA issue key (for example based on the commit message) as an environment variable.

**Comment by dagio** [comment]
Please reopen an issue here --> https://github.com/dagio/post-jira-comment-with-build-details-step
