### ISSUE TITLE
Missing files in repo

### ISSUE THREAD

**Issue by paour** [dagio/post-jira-comment-with-build-details#2]
I'd love to provide a PR for the changes I requested ( #1 ), but your repo seems to be missing important files, such as `step.yml`.

**Comment by dagio** [comment]
The repo for the step is actual another one : https://github.com/dagio/post-jira-comment-with-build-details-step

I should merge them together. I thought at first it would ne nice for reusability but it actually sucks.

I will move the code to the `post-jira-comment-with-build-details-step` repository this week end and ping you so you can open a PR there.

**Comment by paour** [comment]
Sorry to nag you on this… Did you get a chance to move the code?

**Comment by dagio** [comment]
It has been done already. I forgot to notify you.

--> https://github.com/dagio/post-jira-comment-with-build-details-step
